In [125]:
import pandas
import numpy
import matplotlib.pyplot as plot

data_dictionary = pandas.read_csv('source_data/Data_Dictionary_-_Harmonized.csv')

def definerer(itm_name):
    tmp = data_dictionary[data_dictionary['ITM_NAME'] == itm_name]
    if tmp.size > 0:
        print(itm_name)
        print(tmp.iloc[0]['DSCR'])
        print('---')
    else:
        print(itm_name + ' not in data dictionary\n---')

def df_deets(dframe):
    for x in dframe.columns:
        definerer(x)
        
def make_a_set(dframe,column):
    output = set()
    for x in dframe[column]:
        output.add(x)
    return output

In [126]:
updrs_ii = pandas.read_csv('source_data/MDS_UPDRS_Part_II__Patient_Questionnaire.csv')
falls = pandas.read_csv('source_data/Determination_of_Freezing_and_Falls.csv')

updrs_sigfall_base = pandas.read_csv('working_data/updrs_sigfall_base.csv')

In [81]:
# --- Get a collection of PATNO's that exist in both ---
set_updrs = make_a_set(updrs_ii,'PATNO')
set_falls = make_a_set(falls,'PATNO')
shared = list(set_updrs.intersection(set_falls))

#print(shared)

# subset for prototyping
#test = shared[0:1]
test = [shared[0]]
test_updrs = updrs_ii.loc[updrs_ii.PATNO.isin(test)]
test_fall = falls.loc[falls.PATNO.isin(test)]

In [82]:
# f(x) : PATNO,date -> fall within 12months?
# yes but WHAT IS a fall ??

# Create new binary flag SIGFALL (significant fall)
# what are the interesting columns?
# FLLDRVIS
# Fall resulted in outpatient visit to a healthcare provider
# ---
# FLLERVIS
# Fall resulted in ER visit
# ---
# FLLHOSP
# Fall resulted in hospitalization
# ---
# FLLSURG
# Fall resulted in surgery
# ---
# FLLINST
# Fall resulted in institutionalization
fall_columns = ['FLLDRVIS', 'FLLERVIS', 'FLLHOSP', 'FLLSURG','FLLINST' ]

#Â what are the range of values?
fall_unique_values = []
for x in fall_columns:
    fall_unique_values.append(pandas.unique(falls[x]).tolist())
    
print(fall_unique_values)

# Tag & count number of sig fall data entries

def sigfall(row):
    if row['FLLDRVIS'] == 1.0:
        return 1.0
    if row['FLLERVIS'] == 1.0:
        return 1.0
    if row['FLLHOSP'] == 1.0:
        return 1.0
    if row['FLLSURG'] == 1.0:
        return 1.0
    if row['FLLINST'] == 1.0:
        return 1.0
    else:
        return 0.0
    

falls['SIGFALL'] = falls.apply (lambda row: sigfall(row), axis=1)
falls['SIGFALL'].value_counts()

[[nan, 1.0, 0.0], [nan, 1.0, 0.0], [nan, 0.0, 1.0], [nan, 0.0, 1.0], [nan, 0.0, 1.0]]

0.0    1539
1.0     138
Name: SIGFALL, dtype: int64

In [119]:
# So how many rows with UPDRS data have SIGFALL??
# whats the primary key?
#df_deets(updrs_ii)

def sig_get(row):
    patno = row['PATNO']
    infodt = row['INFODT']
    
    s1 = falls[(falls.INFODT == infodt) & (falls.PATNO == patno)]['SIGFALL']
    if s1.empty:    
        return numpy.nan
    else:
        return s1.values[0]


updrs_sigfall = updrs_ii.drop(['REC_ID','EVENT_ID','PAG_NAME','NUPSOURC','ORIG_ENTRY','LAST_UPDATE'], axis=1)
# -- TO DO --- strip superflous columns 

updrs_sigfall['SIGFALL'] = updrs_ii.apply (lambda row: sig_get(row), axis=1)
updrs_sigfall['SIGFALL'].value_counts()

updrs_sigfall_straight = updrs_sigfall_raw.dropna()
updrs_sigfall_straight.shape

0.0    1490
1.0     135
Name: SIGFALL, dtype: int64

In [114]:
updrs_sigfall.head(10)

,PATNO,INFODT,NUPSOURC,NP2SPCH,NP2SALV,NP2SWAL,NP2EAT,NP2DRES,NP2HYGN,NP2HWRT,NP2HOBB,NP2TURN,NP2TRMR,NP2RISE,NP2WALK,NP2FREZ,NP2PTOT,SIGFALL
0,3000,02/2011,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,3000,03/2012,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,3000,02/2013,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,3000,03/2014,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,3000,03/2015,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
5,3000,04/2016,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
6,3000,03/2019,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,3000,05/2021,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,3001,03/2011,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,NaN
9,3001,11/2021,1,0.0,0.0,1.0,1.0,2.0,1.0,3.0,0.0,1.0,1.0,1.0,0.0,0.0,11.0,NaN

In [145]:
#. Computing the +12 month SIGFALL, aka SIGFALL_12M

def get_infodts(patno):
    return list(updrs_sigfall_base[updrs_sigfall_base.PATNO == patno]['INFODT'].values)

def future_sigfall(date,all_dates):
    target = int(date[-4:]) + 1
    output = "FAIL"
    for d in all_dates:
        if int(d[-4:]) == target:
            output = d
            
    return output
             

x = get_infodts(3000)
future_sigfall('03/2016',x)
x

# def get_sigfall_12(row):
#     patno = row['PATNO']
#     infodt = row['INFODT']    
#     dates = get_infodts(patno)
    
#     result = future_sigfall(infodt,dates)
#     if result == "FAIL":
#         return numpy.nan
#     else:
#         return updrs_sigfall_base[(updrs_sigfall_base.INFODT == result ) & (updrs_sigfall_base.PATNO == patno)]['SIGFALL'].values[0]
        

# updrs_sigfall_base['SIGFALL_12M'] = updrs_sigfall_base.apply (lambda row: get_sigfall_12(row), axis=1)

['02/2011',
 '03/2012',
 '02/2013',
 '03/2014',
 '03/2015',
 '04/2016',
 '03/2019',
 '05/2021']

In [144]:
updrs_sigfall_base['SIGFALL_12M'].value_counts()


# Re-doing to get NEXT sigfall, +12 month too vague 

def date_to_tuple(date):
    year = date[-4:]
    month = date[:2]
    return (month,year,date)

def date_sort(dates):
    tup_list = map(date_to_tuple,dates)
    return sorted(tup_list, key = lambda x: (x[1],x[0]))

def get_index(date,dates):
    output = (False,999)    
    for idx, val in enumerate(dates):
            if val[2] == date:
                output = (True,idx)
    return output

def next_sigfall(row):
    output = numpy.nan
    patno = row['PATNO']
    infodt = row['INFODT']    
    dates = get_infodts(patno)
    sorted_dates = date_sort(dates)
    i = get_index(infodt,sorted_dates)
    
    if i[0] == True:
        try:
            next_date_index = i[1] + 1
            next_date = sorted_dates[next_date_index]
            output = updrs_sigfall_base[(updrs_sigfall_base.INFODT == next_date ) & (updrs_sigfall_base.PATNO == patno)]['SIGFALL'].values[0]
        except:
            print()
    return output


# bum = date_sort(get_infodts(3326))
# print(bum)
# get_index('07/2014',bum)

        
updrs_future_sigfall = updrs_sigfall_base.copy()
updrs_future_sigfall['SIGFALL_NEXT'] = updrs_future_sigfall.apply (lambda row: next_sigfall(row), axis=1)
updrs_future_sigfall.to_csv('./working_data/updrs_future_sigfall.csv')

0.0    940
1.0     72
Name: SIGFALL_12M, dtype: int64